"""Regenerate tables and HTML from saved evidence. Standard library only; no API calls."""
import csv
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from curator_bench.costs import branch_cost
from curator_bench.report import render_report
ROOT=Path(__file__).resolve().parents[1]
FAMILIES=['wildchat','long-context','tool-use']

def main():
    rows=[];summaries=[]
    for family in FAMILIES:
        folder=ROOT/'results'/family
        render_report(folder)
        manifest=json.loads((folder/'manifest.json').read_text())
        group=[]
        for cid in manifest['case_ids']:
            record=json.loads((folder/'cases'/(cid+'.json')).read_text())
            item={'dataset':family,'case_id':cid}
            for name,short in [('without_jev','baseline'),('with_jev','curated')]:
                b=record['branches'][name];completion=b['completion'];cost=branch_cost(b,name)
                item.update({short+'_input_tokens':completion['usage']['input_tokens'],short+'_output_tokens':completion['usage']['output_tokens'],short+'_seconds':b['duration_seconds'],short+'_cost_usd':cost['total'],short+'_truncated':b['answer']['truncated']})
                if short=='curated':
                    item['jev_input_tokens']=b.get('jev',{}).get('usage',{}).get('input_tokens',0)
                    item['jev_output_tokens']=b.get('jev',{}).get('usage',{}).get('output_tokens',0)
                    item['original_messages']=b['curation']['original_message_count'];item['retained_messages']=b['curation']['retained_message_count']
            rows.append(item);group.append(item)
        baseline=sum(x['baseline_input_tokens'] for x in group);curated=sum(x['curated_input_tokens'] for x in group)
        summaries.append({'dataset':family,'completed_pairs':len(group),'baseline_main_input_tokens':baseline,'curated_main_input_tokens':curated,'main_input_reduction_pct':100*(1-curated/baseline),'jev_input_tokens':sum(x['jev_input_tokens'] for x in group),'baseline_cost_usd':sum(x['baseline_cost_usd'] for x in group) if all(x['baseline_cost_usd'] is not None for x in group) else None,'curated_cost_usd':sum(x['curated_cost_usd'] for x in group) if all(x['curated_cost_usd'] is not None for x in group) else None,'baseline_mean_seconds':sum(x['baseline_seconds'] for x in group)/len(group),'curated_mean_seconds':sum(x['curated_seconds'] for x in group)/len(group),'truncated_outputs':sum(x['baseline_truncated']+x['curated_truncated'] for x in group)})
    with (ROOT/'results/cases.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    (ROOT/'results/metrics.json').write_text(json.dumps(summaries,indent=2)+'\n')
    lines=['# Recorded results','', 'Generated by `python3 scripts/reproduce.py` from saved live responses. No model calls are made. Quality is ungraded; successful completion is not correctness. Costs are estimates using the historical pricing assumptions in `curator_bench/costs.py`, not invoices.','', '| Dataset | Completed pairs | Main input tokens: full → selected | Reduction | Cost: baseline / with Jev | Mean seconds: baseline / with Jev | Truncated outputs |','|---|---:|---:|---:|---:|---:|---:|']
    for s in summaries:
        money=lambda v: 'unknown' if v is None else f'${v:.4f}'
        lines.append(f"| {s['dataset']} | {s['completed_pairs']} | {s['baseline_main_input_tokens']:,} → {s['curated_main_input_tokens']:,} | {s['main_input_reduction_pct']:.1f}% | {money(s['baseline_cost_usd'])} / {money(s['curated_cost_usd'])} | {s['baseline_mean_seconds']:.2f} / {s['curated_mean_seconds']:.2f} | {s['truncated_outputs']} |")
    lines+=['','Main input reduction excludes Jev processing. With-Jev costs and durations include curation; Jev input/output tokens are in `cases.csv`. Lower main-model input does not imply fewer total system tokens. Durations are single sequential observations, affected by caching, provider load, and output length.','', 'Five tool cases are included; only two ran. Three failed the local byte-budget preflight before requests. See `../benchmarks/tool-budget-details.json`.','', '## Review locally','',*[f'- [{f} paired answers]({f}/review.html)' for f in FAMILIES],'','The HTML pages work after cloning; GitHub displays HTML source rather than hosting the reviewer. Manual ratings stored in browser local storage are not included in these records.','', '## Truncations','']
    lines += [f"- {r['dataset']}/{r['case_id']}: {branch}" for r in rows for branch in ['baseline','curated'] if r[branch+'_truncated']] or ['- None.']
    (ROOT/'results/README.md').write_text('\n'.join(lines)+'\n')
    print(json.dumps(summaries,indent=2))
if __name__=='__main__':main()
